[package]
name = "neojot"
version = "0.0.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "2.0.0-beta", features = [] }

[dependencies]
tauri = { version = "2.0.0-beta", features = [] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4.20"
simplelog = "0.12.1"
anyhow = "1.0.80"
dirs = "5.0.1"
open = "5.0.1"
url = "2.5.0"
tauri-plugin-fs = "2.0.0-beta.1"
tauri-plugin-autostart = "2.0.0-beta.1"
regex = "1.10.3"

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
